"use strict";

var blockElements = ["address", "article", "aside", "blockquote", "details", "dialog", "dd", "div", "dl", "dt", "fieldset", "figcaption", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "hr", "li", "main", "nav", "ol", "p", "pre", "section", "table", "ul"];
var trustedTags = ["a", "abbr", "ad", "audio", "b", "blockquote", "br", "code", "col", "colgroup", "dd", "del", "dl", "dt", "div", "em", "fieldset", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "ins", "label", "legend", "li", "ol", "p", "q", "source", "span", "strong", "sub", "sup", "table", "tbody", "td", "tfoot", "th", "thead", "tr", "title", "u", "ul", "video"];
var trustAttrs = ["align", "allowfullscreen", "alt", "app-id", "appid", "apid", "author", "autoplay", "border", "cellpadding", "cellspacing", "class", "color", "colspan", "controls", "data-src", "dir", "face", "frameborder", "height", "href", "id", "ignore", "loop", "media", "muted", "name", "path", "poster", "rowspan", "size", "span", "src", "start", "style", "type", "unit-id", "unitId", "width", "xmlns"];
var blockTags = ["address", "article", "aside", "body", "center", "cite", "footer", "header", "html", "nav", "pre", "section"];
var selfClosingTags = ["area", "base", "basefont", "bgsound", "br", "col", "command", "embed", "frame", "hr", "image", "img", "input", "isindex", "keygen", "link", "menuitem", "meta", "nextid", "param", "source", "track", "wbr"];
var ignoreTags = ["area", "base", "basefont", "canvas", "circle", "command", "ellipse", "frame", "head", "input", "isindex", "keygen", "line", "link", "map", "meta", "param", "path", "polygon", "rect", "script", "source", "svg", "textarea", "track", "use", "wbr"];
var richOnlyTags = ["a", "colgroup", "fieldset", "legend", "picture", "table", "tbody", "td", "tfoot", "th", "thead", "tr"];
var blankChar = [" ", "\xA0", "\t", "\r", "\n", "\f"];